apiVersion: v1
kind: ServiceAccount
metadata:
  name: ruleshift-gateway
  namespace: ruleshift-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ruleshift-gateway-module-scheduler
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["limitranges"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ruleshift-gateway-module-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ruleshift-gateway-module-scheduler
subjects:
  - kind: ServiceAccount
    name: ruleshift-gateway
    namespace: ruleshift-core

